stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: maven:3-eclipse-temurin-17
  script:
  - git clone https://oauth2:$MOHANED_TOKEN@gitlab.fdmci.hva.nl/se-specialization-2023-2/projects-tse1/ewamon/foryou
  - cd foryou
    
  - git clone https://oauth2:$GITHUB_MOHANED_TOKEN@github.com/ForyouHQ/Foryou.git .github
  - ls -la  # List files in the current directory
  - ls -la .github  # List files in the .github directory
  - ls -la .github/workflows  # List files in the .github/workflows directory

  - git remote set-url --push origin https://oauth2:$GITHUB_MOHANED_TOKEN@github.com/ForyouHQ/Foryou.git

  - git checkout main || git checkout -b main
  - git pull origin main
  - git push --force origin main
  - git checkout develop || git checkout -b develop
  - git pull origin develop
  - git push --force origin develop
  - git push --mirror
  only:
    - main
    - develop
  tags:
    - hva
