stages:
  - mirror

mirror_to_github:
  stage: mirror
  script:
    - git clone https://gitlab.fdmci.hva.nl/se-specialization-2023-2/projects-tse1/ewamon/foryou
    - cd foryou
    - git remote set-url --push origin https://github.com/ForyouHQ/Foryou.git
    - git push --mirror
  only:
    - main 
    - develop
  tags:
    - hva