stages:
  - mirror
  - build-and-push-backend
  - build-and-push-frontend

variables:
  DOCKER_IMAGE_BACKEND: ForYouHQ/foryou-server
  DOCKER_IMAGE_FRONTEND: ForYouHQ/foryou-frontend

mirror_to_github:
  stage: mirror
  image: maven:3-eclipse-temurin-17
  script:
  - git config --global user.email "contactforyouhq@gmail.com"
  - git config --global user.name "ForyouHQ"

  - git clone https://oauth2:$MOHANED_TOKEN@gitlab.fdmci.hva.nl/se-specialization-2023-2/projects-tse1/ewamon/foryou
  - cd foryou

  - git remote rename origin gitlab
  - git remote add github https://oauth2:$GITHUB_MOHANED_TOKEN@github.com/ForyouHQ/Foryou.git

  - git fetch gitlab main
  - git checkout main
  - git pull gitlab main
  - git fetch github main
  - git merge github/main
  - git push github main

  - git fetch gitlab develop
  - git checkout develop
  - git pull gitlab develop
  - git fetch github develop
  - git merge github/develop
  - git push github develop
  only:
    - main
    - develop
  tags:
    - hva

build-and-push-backend:
  stage: build-and-push-backend
  image: maven:3-eclipse-temurin-17
  script:
    - cd foryou-server
    - docker build --tag $DOCKER_IMAGE_BACKEND .
    - docker push $DOCKER_IMAGE_BACKEND
  only:
    - develop
  tags:
    - hva  

build-and-push-frontend:
  stage: build-and-push-frontend
  image: maven:3-eclipse-temurin-17
  script:
    - cd foryou-frontend
    - docker build --tag $DOCKER_IMAGE_FRONTEND .
    - docker push $DOCKER_IMAGE_FRONTEND
  only:
    - develop
  tags:
    - hva  